### ISSUE TITLE
fb_token no longer auto fetched

### ISSUE THREAD

**Issue by cukubik** [tarraschk/TinderAutoLike#10]
After facebook updates the protocol to obtain an oAuthToken in mid August, this project is no longer able to get the "fb_token". Would it be possible to update it as described in the Tinder API gist? 

See this solution:
https://gist.github.com/rtt/10403467#gistcomment-1846343

Thanks,
Cukubik

**Comment by tarraschk** [comment]
Hey Cukubik,

Thanks for your message.

I'm on it.

best,

**Comment by tarraschk** [comment]
It's done!

Please feel free to try it and tell me if it is okay for you :)

**Comment by cukubik** [comment]
Thanks for prompt update.

Here's a small issue:

==== FACEBOOK ====
* Fetching Facebook data...
  - Fetching your Facebook Tinder token...
=> My FB_TOKEN is _oh my confidentiality fikibok cukubik laylaylay_
  - Fetching your Facebook ID...
TinderAutoLike.rb:75:in `<main>': undefined method `captures' for nil:NilClass (NoMethodError)


Line 75 is when it is fetching the fb_id. I don't know ruby, but you've used the "captures" method for fb_token above, so I'm guessing there's a small syntax error in 75. On the other hand, Facebook no longer needs a fb_id there. So, I've deleted all the references to fb_id and this program works like a charm.


Thanks,
cukubik

**Comment by cukubik** [comment]
A side note:
When you've added mechanize here, the bundle install failed on my machine on nokogiri. Turns out El Capitan has added some security features that the default gem installation dir is no longer user writable. 

So maybe it's a good idea to include this command in README, 
sudo gem install -n /usr/local/bin nokogiri -v '1.6.8'

Reference:
http://stackoverflow.com/questions/32891965/error-while-executing-gem-errnoeperm-operation-not-permitted

Thanks,
cukubik

**Comment by tarraschk** [comment]
Hey,

thank you for this information. I did not know that FB_ID was no longer required.

=> I just removed it from my update.

Also, I just updated the README.

Finally, thank you for this little update, as it gave me back some envy to write a full GUI for the app.

Best,
