### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PaulElM** [tarraschk/TinderAutoLike#11]
┌────────────────────────────────────────────────────────────────────┐
│ Tinder Ruby AutoLiker v2.0                                         │
├────────────────────────────────────────────────────────────────────┤
│ Copyright c 2014-2016 Maxime Alay-Eddine @maximeae                 │
├────────────────────────────────────────────────────────────────────┤
│ Licensed under the MIT license.                                    │
└────────────────────────────────────────────────────────────────────┘
==== FACEBOOK ====
* Fetching Facebook data...
  - Fetching your Facebook Tinder token...
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_con
nect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verif
y failed (OpenSSL::SSL::SSLError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:923:in `bloc
k in connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/timeout.rb:75:in `timeou
t'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:923:in `conn
ect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_s
tart'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:858:in `star
t'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persi
stent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persi
stent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persi
stent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/mechanize-2.7.
5/lib/mechanize/http/agent.rb:274:in `fetch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/mechanize-2.7.
5/lib/mechanize.rb:464:in `get'
        from TinderAutoLike.rb:61:in `<main>'

**Comment by tarraschk** [comment]
Hi there,

please next time say `Hello` and give some details about your issue.
It does not hurt and it will really makes me helpful for you ;).

For your issue, it is not related to my project but to your machine: your computer has not the required certificates to certify that you're talking to the real Facebook website!

I just pushed an update of my script that should handle everything for you properly.
Can you confirm that it works?

1. Update my script by downloading it again
2. Run `bundle install`
3. Edit your credentials in my script.
4. Run `bundle exec ruby TinderAutoLike.rb` and profit!

Best,

**Comment by PaulElM** [comment]
Hello Hello Hellooo,
Im sorry for that!!!
I test it and it work!!!! Thank u very much!
I will try to write the code in php now!

**Comment by tarraschk** [comment]
Perfect!
