### ISSUE TITLE
If I get user IDs starting with "tinder_rate_limited_id_" does it mean this script is not working?

### ISSUE THREAD

**Issue by iamrcr** [tarraschk/TinderAutoLike#12]
I open targets.txt and almost all user IDs start with  "tinder_rate_limited_id_" .

Does it mean this script is not actually liking this user ID? It seems like it has reached the like limit.

**Comment by tarraschk** [comment]
Yep.

It means it has reached the like limit at this point and should be stopped.

I chose to let it parse new potential matches in order to fetch their pictures and details, to put it in GUI (under slow but active development).

**Comment by iamrcr** [comment]
I'm running this script on an infinite while loop, 24/7.
It gets "tinder_rate_limited_id_" 's for some hours but then it goes back to normal.
It seems it's capable of yielding an average of 280 legitimate likes per day.

**Comment by iamrcr** [comment]
The block lasts for about 13 hours. Then it's a good idea to run this script every 13 hours. It's also a good idea to run it more than once, maybe about ten times, as it takes some time for it to get completely blocked.
