### ISSUE TITLE
Can't seem to be able to run it

### ISSUE THREAD

**Issue by jolio007** [tarraschk/TinderAutoLike#14]
I wrote this in the command like after successfully having installed bundler ->

>  bundle install bundle exec ruby TinderAutoLike.rb

![error message1](https://cloud.githubusercontent.com/assets/20499453/24142121/e80b61c0-0e25-11e7-8b01-67d451496961.png)

Sorry if this is a rookie error. I'm fairly new to the game

**Comment by tarraschk** [comment]
Hi

`bundle install` and `bundle exec ruby TinderAutoLike.rb` are two different commands and should be run separately.

First type `bundle install` and then hit Enter to run it.
Then type `bundle exec ruby TinderAutoLike.rb` and then hit Enter to run it.

Don't forget to set your login / password in the TinderAutoLike.rb file.
