### ISSUE TITLE
TinderAutoLike.rb:24:in `<main>': undefined local variable or method `‘adam' for main:Object (NameError)

### ISSUE THREAD

**Issue by jmcmatrixs** [tarraschk/TinderAutoLike#5]
TinderAutoLike.rb:24:in `<main>': undefined local variable or method `‘adam' for main:Object (NameError)
Adams-Air:TinderAutoLike-master adamwebb$ 

So I've followed the instructions
I CD into my Downloads
CD Directory where it's stored
bundle Install
bundle exec ruby TinderAutoLike.rb

I've set my username and pw for example to
adam.something@gmail.com
Password1

and doesn't work.

**Comment by tarraschk** [comment]
Hey Adam,

I think that you wrote:
```
myLogin = adam.something@gmail.com
myPassword = Password1
```
didn't you?

In that case, you just forgot the quotes around your email address and password.
As a result, Ruby thinks ```adam``` is an object/a variable, but as it is undefined it won't work.

You must replace it with:
```
myLogin = 'adam.something@gmail.com'
myPassword = 'Password1'
```

**Comment by jmcmatrixs** [comment]
myLogin = ‘adam.something1@hotmail.co.uk’
myPassword = ‘actualpassword1’

I'm using this  ' ' around it, and it still doesn't work :)

**Comment by tarraschk** [comment]
Did you try with just:
```
bundle install
bundle exec ruby TinderAutoLike.rb
```
as specified in the Readme?

Bundler should compute for you the dependencies, instead of asking you to install manually each gem.

**Comment by jmcmatrixs** [comment]
''''
Adams-Air:TinderAutoLike-master adamwebb$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using ffi 1.9.10
Using childprocess 0.5.6
Using multipart-post 2.0.0
Installing faraday 0.9.1
Installing faraday_middleware 0.10.0
Installing json 1.8.3 with native extensions
Using multi_json 1.11.2
Using rubyzip 1.1.7
Using websocket 1.2.2
Using selenium-webdriver 2.47.1
Installing watir-webdriver 0.8.0
Using bundler 1.10.6
Bundle complete! 4 Gemfile dependencies, 12 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Adams-Air:TinderAutoLike-master adamwebb$ bundle exec ruby TinderAutoLike.rb
TinderAutoLike.rb:30: syntax error, unexpected tIDENTIFIER, expecting end-of-input
require 'faraday'
                ^
Adams-Air:TinderAutoLike-master adamwebb$ bundle exec ruby TinderAutoLike.rb
''''

**Comment by tarraschk** [comment]
Well, that's really weird...
Have you edited any other line than the Facebook login and password?
If so, could you copy/paste the code here?

**Comment by jmcmatrixs** [comment]
I've only edited the username and password part as it says In your readme

On 10 September 2015, at 23:48, Maxime Alay-Eddine <notifications@github.com> wrote:

Well, that's really weird...
Have you edited any other line than the Facebook login and password?
If so, could you copy/paste the code here?

**Comment by jmcmatrixs** [comment]
My ruby version is 2.23, and I have rails installed too.

On 10 September 2015, at 23:48, Maxime Alay-Eddine <notifications@github.com> wrote:

Well, that's really weird...
Have you edited any other line than the Facebook login and password?
If so, could you copy/paste the code here?

**Comment by tarraschk** [comment]
Okay so it might be an encoding issue.

Did you copy / paste the code of my script, or directly cloned it with git?
