### ISSUE TITLE
Does this library still work?

### ISSUE THREAD

**Issue by russelltaylor05** [tarraschk/TinderAutoLike#6]
I'm getting the following error.

```
Users/russell/.rvm/gems/ruby-2.0.0-p576@railstutorial_rails_4_0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/wait.rb:44:in `until': timed out after 30 seconds, waiting for {:class=>"profilePicThumb", :tag_name=>"a"} to become present (Watir::Wait::TimeoutError)
	from /Users/russell/.rvm/gems/ruby-2.0.0-p576@railstutorial_rails_4_0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/wait.rb:114:in `method_missing'
	from TinderAutoLike.rb:72:in `<main>'
```

**Comment by tarraschk** [comment]
Hello there,

yes it still works :).

Could you please give me more details on your error, so that I could help you?

Are you sure that your Facebook login and password are correct? Did you check if the login was working (maybe Facebook blocked you, thinking you were a bot).

Best,

Maxime AE

**Comment by adi2014** [comment]
hi am getting this error 
E:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 er
rno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday:
:SSLError)
        from E:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from E:/Ruby22/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from E:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from E:/Ruby22/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from E:/Ruby22/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from E:/Ruby22/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapte
r/net_http.rb:82:in `perform_request'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapte
r/net_http.rb:40:in `block in call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapte
r/net_http.rb:87:in `with_net_http_connection'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapte
r/net_http.rb:32:in `call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/respon
se.rb:8:in `call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/respon
se/logger.rb:24:in `call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/fa
raday_middleware/request/encode_json.rb:23:in `call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_b
uilder.rb:139:in `build_response'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connec
tion.rb:377:in `run_request'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connec
tion.rb:177:in `post'
        from TinderAutoLike.rb:90:in `<main>'

so how to solve it

**Comment by tarraschk** [comment]
Hello adi.

This problem does not come from my code, but rather from your certificates :).

Just follow this issue:
https://github.com/google/google-api-ruby-client/issues/235

Best,
