### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by boyshawn** [tarraschk/TinderAutoLike#7]
I think that the app is not working anymore, I run it any it just pop up and then close.

**Comment by tarraschk** [comment]
Hi there,

Could you give us more details?

I just tried it again, and it worked well :).

Best,

**Comment by boyshawn** [comment]
Can you have an enhancement to not close the windows automatically when there is an error in the program?

I open the program and there is an error, and it immediately close the error. 

Anyway, I manage to capture the error using screenshot. 
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55in 'require': cannot load such file --faraday (LoadError) 
from C:/Ruby23-x64/ruby/2.3.0/rubygemsd/core_ext/kernel_require.fb:55: in 'require'
from <path to TinderAutoLike-master/TinderAuotLike.rb:30:in '<main>'

**Comment by AdamWebb1** [comment]
I think The latest binary gem doesn't include pre-compiled oci8lib_230.because ruby 2.3.0 was released only a week ago, so you should use ruby 2.2.4.

**Comment by boyshawn** [comment]
Nah, 2.2.4 doesn't work. It needs a specific library. I am using 2.2.4 (X64)

C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- faraday (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from TinderAutoLike.rb:30:in `<main>'

**Comment by tarraschk** [comment]
Did you run `bundle install` ? and then `bundle exec ruby TinderAutoLike.rb` ?

Looks like a dependency issue, as it does not find the Faraday gem.

**Comment by boyshawn** [comment]
bundle install? 
The result is as below:
'bundle' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tarraschk** [comment]
1. Install ruby
2. Install bundler with `gem install bundler`
3. Run `bundle install` to install the dependencies
4. Run `bundle exec ruby TinderAutoLike.rb` to launch the program

**Comment by boyshawn** [comment]
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/windows.rb:1:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/windows.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess.rb:176:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess.rb:176:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver.rb:20:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver.rb:20:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium-webdriver.rb:20:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium-webdriver.rb:20:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver.rb:1:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver.rb:1:in `<top (required)>'
        from TinderAutoLike.rb:32:in `require'
        from TinderAutoLike.rb:32:in `<main>'

**Comment by tarraschk** [comment]
These errors are not from the bot himself, but rather from a dependency issue.

What did you type exactly to get those?

**Comment by boyshawn** [comment]
Okay.

`C:\Users\>E:

E:\>cd TinderAutoLike-master

E:\TinderAutoLike-master>dir
 Volume in drive E is Data SSD
 Volume Serial Number is B0C4-7498

 Directory of E:\TinderAutoLike-master

30/04/2016  11:05 AM    <DIR>          .
30/04/2016  11:05 AM    <DIR>          ..
20/04/2016  09:35 PM               622 .gitignore
20/04/2016  09:35 PM               102 Gemfile
26/04/2016  01:25 AM               627 Gemfile.lock
20/04/2016  09:35 PM             1,085 LICENSE
20/04/2016  09:35 PM             2,320 README.md
26/04/2016  01:30 AM             5,820 TinderAutoLike.rb
               6 File(s)         10,576 bytes
               2 Dir(s)  104,949,981,184 bytes free

E:\TinderAutoLike-master>gem install bundle
ERROR:  Interrupted
Terminate batch job (Y/N)? y

E:\TinderAutoLike-master>gem install bundler
Fetching: bundler-1.12.0.gem (100%)
Successfully installed bundler-1.12.0
Parsing documentation for bundler-1.12.0
Installing ri documentation for bundler-1.12.0
Done installing documentation for bundler after 4 seconds
1 gem installed

E:\TinderAutoLike-master>bundle install
Checksum of /versions does not match the checksum provided by server! Something
is wrong.

E:\TinderAutoLike-master>bundle exec ruby TinderAutoLike.rb
Could not find faraday_middleware-0.10.0 in any of the sources
Run `bundle install` to install missing gems.`

**Comment by tarraschk** [comment]
The error comes from here:
```
E:\TinderAutoLike-master>bundle install
Checksum of /versions does not match the checksum provided by server! Something
is wrong.
```

This error comes from your Bundler installation, which can not install dependencies of the TinderBot.

Solution seems to be as following:
```bash
gem uninstall bundler
gem install bundler -v 1.9
````

Then, install again the dependencies with:
```
bundle install
```

Source:
http://stackoverflow.com/questions/35315712/rails-initialization-checksum-error
https://github.com/railsinstaller/railsinstaller-windows/issues/69

**Comment by boyshawn** [comment]
I still don't get to install the JSON package

E:\TinderAutoLike-master>bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using ffi 1.9.10
Using childprocess 0.5.9
Using multipart-post 2.0.0
Using faraday 0.9.2
Installing faraday_middleware 0.10.0

Gem::InstallError: The 'json' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

E:\TinderAutoLike-master>gem install json -v 1.8.3
ERROR:  Error installing json:
        The 'json' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

**Comment by andreraf** [comment]
When I type bundle install this is what i come up with: 
user$ bundle install
Could not locate Gemfile or .bundle/ directory
Any solutions to this?

**Comment by tarraschk** [comment]
@boyshawn : you should read Ruby tutorials, especially if you're using Windows.

The error you had told you:
```
Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
```

=> Follow the given instructions, then run again my program and everything will be right.

@andreraf : you have to run `bundle install` in the directory where you downloaded my files.

**Comment by andreraf** [comment]
How exactly do I run that in the correct directory? I'm using a mac osx 10.10. 
After I run `bundle install` I get a list of options, 
```
1 : diff-lcs
2 : rspec-support
3 : rspec-core
4 : rspec-expectations
5 : rspec-mocks
6 : rspec
7 : bundler
0 : - exit -

```
then..
```
bundle exec ruby TinderAutoLike.rb
ruby: No such file or directory -- TinderAutoLike.rb (LoadError)
```

Thanks for your help

**Comment by andreraf** [comment]
Got it nevermind.
