### ISSUE TITLE
TinderAutoLike.rb:72:in `<main>': undefined method `captures' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hdogg** [tarraschk/TinderAutoLike#8]
After fetching FB token, the next line I get is:

TinderAutoLike.rb:72:in `<main>': undefined method `captures' for nil:NilClass (NoMethodError)

and then nothing happens.

**Comment by tarraschk** [comment]
Hey,

could you copy/paste the complete exact output of the program?

It might be an error in your Facebook credentials.

Could you check that you have written
```
myLogin = 'REPLACE_BY_YOUR_EMAIL'
myPassword = 'REPLACE_BY_YOUR_PASSWORD'
```
(please keep the simple quotes)

Best,

**Comment by hdogg** [comment]
Here's the complete output:
Howards-MBP:TinderAutoLike-master howard$ bundle exec ruby TinderAutoLike.rb ┌────────────────────────────────────────────────────────────────────┐ │ Tinder Ruby AutoLiker v1.0.1 │ ├────────────────────────────────────────────────────────────────────┤ │ Copyright © 2014 Maxime Alay-Eddine @tarraschk │ │ Copyright © 2014 ARGAUS SAS Cybersecurity (http://www.argaus.fr) │ ├────────────────────────────────────────────────────────────────────┤ │ Licensed under the MIT license. │ ├────────────────────────────────────────────────────────────────────┤ │ This script has been made to do a little social experience, trying | | to apply A/B testing to Tinder. | │ Please do not abuse this script. Try to meet girls in real life | | and preserve the dignity of human relationships. | └────────────────────────────────────────────────────────────────────┘ ==== FACEBOOK ==== Fetching Facebook data... Fetching your Facebook Tinder token... Fetching your Facebook ID... My FB_TOKEN is
EAAGm0PX4ZCpsBADu3kdMbhRXmuZAsRUfi5UZCZCYZByjKqCoqJxj3AMoBaMWq9XB7FZA6AtlKRSvYSPiBRwcEBSZC2ApViNL7gOZCr3tEDG27gjyZAXNvz8578gAxmuxjp4DNooAXSYnEkPxHCaavB6du0k7oBWgAZB5TsPIzOiZC16A6rRWCZBU0D8b TinderAutoLike.rb:72:in `<main>': undefined method `captures' for nil:NilClass
(NoMethodError) Howards-MBP:TinderAutoLike-master howard$





On Wed, May 18, 2016 1:09 PM, Maxime Alay-Eddine notifications@github.com wrote:
Hey,

could you copy/paste the complete exact output of the program?

It might be an error in your Facebook credentials.

Could you check that you have written

myLogin = 'REPLACE_BY_YOUR_EMAIL'
myPassword = 'REPLACE_BY_YOUR_PASSWORD'


(please keep the simple quotes)

Best,

**Comment by tarraschk** [comment]
Thank you.

The program crashes during the execution of these lines:

```
browser.goto'https://www.facebook.com/profile.php'
fb_id = /fbid=(.*)&set/.match(browser.link(:class =>"profilePicThumb").when_present.href).captures[0]
puts 'My FB_ID is '+fb_id
```

It sounds like you do not load properly the ```<a class="profilePicThumb">``` tag from Facebook, which contains your Profile Pic and is tagged with your Facebook_ID.

1. Can you confirm that the FB login screen is properly automatically filled by the script?
2. Can you confirm that the script does log you in Facebook properly?
3. Can you confirm that after being logged in, you are redirected to your profile page?
4. If so, is your profile page fully loaded?

Best,
