### ISSUE TITLE
Missing a selenium driver?

### ISSUE THREAD

**Issue by TaxiCab88** [tarraschk/TinderAutoLike#9]
Fetching Facebook data...
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable': unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/common/socket_lock.rb:43:in `locked'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/firefox/bridge.rb:43:in `initialize'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.3/lib/selenium/webdriver.rb:84:in `for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/browser.rb:46:in `initialize'
        from TinderAutoLike.rb:60:in `new'
        from TinderAutoLike.rb:60:in `<main>'

**Comment by tarraschk** [comment]
Hi there,

Have you tried ```gem update selenium-webdriver``` ?

Source:http://stackoverflow.com/questions/14303161/unable-to-obtain-stable-firefox-connection-in-60-seconds-127-0-0-17055

**Comment by tarraschk** [comment]
Hi there,

@TaxiCab88 please note that selenium is no longer required and that everything should be better for you now :).

Best,

**Comment by TaxiCab88** [comment]
Right on, thanks!
